# Generated by Django 5.0.6 on 2024-07-08 22:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DATOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conv', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_doc', models.CharField(max_length=100)),
                ('numero_doc', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('tipo_certificado', models.CharField(max_length=100)),
                ('formato_entrega', models.CharField(max_length=100)),
                ('vigencia', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('unidad_organizacional', models.CharField(max_length=100)),
                ('token_andesid', models.CharField(max_length=100)),
                ('universidad', models.CharField(max_length=100)),
                ('facultad', models.CharField(max_length=100)),
                ('titulo_profesional', models.CharField(max_length=100)),
                ('matricula_profesional', models.CharField(max_length=100)),
                ('radicado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FORMATO_ENTREGA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_convenio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FormatoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionFirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SOLICITUD_CERT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_certificado', models.IntegerField()),
                ('id_convenio', models.IntegerField()),
                ('id_datos', models.IntegerField()),
                ('nombre_cert', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_CERT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cert', models.CharField(max_length=100)),
                ('id_convenio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VIGENCIA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cert', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VigenciaCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CONVENIO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('certificados_permi', models.CharField(max_length=100)),
                ('o_cert_permi', models.CharField(max_length=100)),
                ('o_firmado_permi', models.CharField(max_length=100)),
                ('o_otp_permi', models.CharField(max_length=100)),
                ('vigencias_permi', models.CharField(max_length=100)),
                ('formatos_entrega_permi', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100, null=True)),
                ('color_primario', models.CharField(max_length=100)),
                ('color_secundario', models.CharField(max_length=100)),
                ('id_vigenica', models.IntegerField(null=True)),
                ('usuario_convenio', models.CharField(max_length=100)),
                ('imagen_banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('contraseña_convenio', models.TextField(blank=True, null=True)),
                ('usuario_weservice', models.CharField(max_length=100, null=True)),
                ('contraseña_webservice', models.CharField(max_length=100, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CONVENIO', to=settings.AUTH_USER_MODEL)),
                ('formatos_entrega', models.ManyToManyField(related_name='convenios', to='dashboards.formatoentrega')),
                ('operaciones_certificado', models.ManyToManyField(related_name='convenios', to='dashboards.operacioncertificado')),
                ('operaciones_firmado', models.ManyToManyField(related_name='convenios', to='dashboards.operacionfirmado')),
                ('operaciones_otp', models.ManyToManyField(related_name='convenios', to='dashboards.operacionotp')),
                ('certificados_seleccionados', models.ManyToManyField(related_name='convenios', to='dashboards.tipo_cert')),
                ('tipos_certificado', models.ManyToManyField(related_name='convenios', to='dashboards.tipocertificado')),
                ('vigencias_certificado', models.ManyToManyField(related_name='convenios', to='dashboards.vigenciacertificado')),
            ],
        ),
        migrations.CreateModel(
            name='CONFI_CERTIFICADOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_certificado', models.CharField(max_length=255)),
                ('vigencias', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('formatos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('id_convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.convenio')),
            ],
        ),
    ]
